application: enteryourappname
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: statics/favicon.ico
  upload: statics/favicon.ico

- url: /statics
  static_dir: statics

- url: /.*
  script: _go_app
